<?php

namespace AppBundle\Repository\Blog;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBlogPostsByParams($params)
    {
        $em = $this->getEntityManager();

        $postsQuery = $em->createQueryBuilder()
            ->select('p', 't')
            ->from('AppBundle:Blog\Post', 'p')
            ->leftJoin('p.tags', 't')
            ->orderBy('p.createdAt' ,'DESC');

        if ($params->has('tag') && $params->get('tag')){
            $postsQuery->where('t.name = ?1')
                ->setParameter(1, $params->get('tag'));
        }

        if ($params->has('title') && $params->get('title')) {
            $postsQuery->where(
                $postsQuery->expr()->like('p.title', ':title')
            )
                ->setParameter('title', '%' . $params->get('title') . '%');
        }
        return $postsQuery->getQuery()->getResult();
    }
}
